namespace VsChromiumMcp.Shared;

public static class Paths {
    public const string PipeName = "VsChromiumMcp.Daemon";

    public static string AppDataRoot { get; } = Path.Combine(
        Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData),
        "VsChromiumMcp");

    public static string LogsDir { get; } = Path.Combine(AppDataRoot, "logs");
    public static string ProjectsFile { get; } = Path.Combine(AppDataRoot, "projects.json");
    public static string DaemonPidFile { get; } = Path.Combine(AppDataRoot, "daemon.pid");
    public static string DaemonReadyFile { get; } = Path.Combine(AppDataRoot, "daemon.ready");

    public static void EnsureCreated() {
        Directory.CreateDirectory(AppDataRoot);
        Directory.CreateDirectory(LogsDir);
    }

    public const string VsChromiumProjectFileName = "vs-chromium-project.txt";

    public static string DefaultProjectFileContent { get; } =
        """
        # Generated by VsChromiumMcp. Tunable; see vs-chromium docs for syntax.
        # https://chromium.github.io/vs-chromium/#vs-chromium-project-file

        [SourceExplorer.ignore]
        # Common build/output directories - paths excluded from the file system tree entirely.
        .git/
        .svn/
        .hg/
        node_modules/
        bin/
        obj/
        target/
        dist/
        build/
        out/
        .vs/
        .idea/
        __pycache__/
        .next/
        .cache/

        [SearchableFiles.include]
        *

        [SearchableFiles.ignore]
        """;
}
